/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BranchStats {
  'branch' : string,
  'examRegDoFirst' : bigint,
  'examRegErrors' : bigint,
  'examRegDone' : bigint,
  'examRegRedo' : bigint,
  'examRegTotal' : bigint,
  'enrollmentErrors' : bigint,
  'enrollmentTotal' : bigint,
}
export interface CourseRecord {
  'duration' : string,
  'yearKey' : string,
  'category' : string,
  'courseName' : string,
  'courseId' : string,
  'college' : string,
}
export interface EditedRecord {
  'id' : string,
  'field' : string,
  'branch' : string,
  'oldValue' : string,
  'studentId' : string,
  'yearKey' : string,
  'newValue' : string,
  'recordType' : string,
  'timestamp' : bigint,
  'editedBy' : string,
  'college' : string,
}
export interface EnrollmentPage {
  'hasMore' : boolean,
  'data' : Array<EnrollmentRecord>,
  'totalCount' : bigint,
}
export interface EnrollmentRecord {
  'id' : string,
  'status' : string,
  'branch' : string,
  'duration' : string,
  'studentId' : string,
  'yearKey' : string,
  'errorDescription' : string,
  'email' : string,
  'errorType' : string,
  'courseName' : string,
  'courseId' : string,
  'college' : string,
  'hasError' : boolean,
}
export interface ExamRegPage {
  'hasMore' : boolean,
  'data' : Array<ExamRegRecord>,
  'totalCount' : bigint,
}
export interface ExamRegRecord {
  'id' : string,
  'branch' : string,
  'paymentStatus' : string,
  'studentId' : string,
  'yearKey' : string,
  'errorDescription' : string,
  'email' : string,
  'errorType' : string,
  'registrationStatus' : string,
  'courseName' : string,
  'courseId' : string,
  'college' : string,
  'hasError' : boolean,
}
export interface ExamShufflePage {
  'hasMore' : boolean,
  'data' : Array<ExamShuffleRecord>,
  'totalCount' : bigint,
}
export interface ExamShuffleRecord {
  'id' : string,
  'branch' : string,
  'studentId' : string,
  'yearKey' : string,
  'examCenter' : string,
  'email' : string,
  'rollNo' : string,
  'examDate' : string,
  'courseName' : string,
  'courseId' : string,
  'timeSlot' : string,
  'college' : string,
  'hallTicketNo' : string,
  'seatingPosition' : string,
}
export interface FileSnapshot {
  'id' : string,
  'isActive' : boolean,
  'filename' : string,
  'timestamp' : bigint,
  'recordCount' : bigint,
}
export interface HODPermission {
  'branch' : string,
  'yearKey' : string,
  'editCredits' : bigint,
  'uploadCredits' : bigint,
  'college' : string,
}
export interface OverviewStats {
  'examRegDoFirst' : bigint,
  'cleanEnrollment' : bigint,
  'totalEnrolled' : bigint,
  'examRegErrors' : bigint,
  'examRegDone' : bigint,
  'examRegRedo' : bigint,
  'enrollmentErrors' : bigint,
  'totalRegistered' : bigint,
}
export interface _SERVICE {
  'editEnrollmentRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      EnrollmentRecord,
      string,
      string,
      string,
      string,
    ],
    boolean
  >,
  'editExamRegRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      ExamRegRecord,
      string,
      string,
      string,
      string,
    ],
    boolean
  >,
  'getAllCourses' : ActorMethod<[string, string], Array<CourseRecord>>,
  'getAllEditedRecords' : ActorMethod<[string, string], Array<EditedRecord>>,
  'getAllEnrollmentErrors' : ActorMethod<
    [string, string],
    Array<EnrollmentRecord>
  >,
  'getAllEnrollmentRecords' : ActorMethod<
    [string, string],
    Array<EnrollmentRecord>
  >,
  'getAllExamRegErrors' : ActorMethod<[string, string], Array<ExamRegRecord>>,
  'getAllExamRegRecords' : ActorMethod<[string, string], Array<ExamRegRecord>>,
  'getAllExamShuffle' : ActorMethod<[string, string], Array<ExamShuffleRecord>>,
  'getAllHODPermissions' : ActorMethod<[string, string], Array<HODPermission>>,
  'getCoursesByBranchAndCollege' : ActorMethod<
    [string, string, [] | [string]],
    Array<CourseRecord>
  >,
  'getEditedRecords' : ActorMethod<
    [string, string, string],
    Array<EditedRecord>
  >,
  'getEnrollmentByBranch' : ActorMethod<
    [string, string, string],
    Array<EnrollmentRecord>
  >,
  'getEnrollmentRecordsPaged' : ActorMethod<
    [string, string, [] | [string], [] | [boolean], bigint, bigint],
    EnrollmentPage
  >,
  'getExamRegByBranch' : ActorMethod<
    [string, string, string],
    Array<ExamRegRecord>
  >,
  'getExamRegRecordsPaged' : ActorMethod<
    [string, string, [] | [string], [] | [boolean], bigint, bigint],
    ExamRegPage
  >,
  'getExamShuffleByStudent' : ActorMethod<
    [string, string, string],
    Array<ExamShuffleRecord>
  >,
  'getExamShufflePaged' : ActorMethod<
    [string, string, bigint, bigint],
    ExamShufflePage
  >,
  'getFileSnapshots' : ActorMethod<
    [string, string, string],
    Array<FileSnapshot>
  >,
  'getHODPermission' : ActorMethod<
    [string, string, string],
    [] | [HODPermission]
  >,
  'getOverviewStats' : ActorMethod<[string, string], OverviewStats>,
  'getStatsByBranch' : ActorMethod<[string, string, string], BranchStats>,
  'getStudentEnrollment' : ActorMethod<
    [string, string, string],
    Array<EnrollmentRecord>
  >,
  'getStudentExamReg' : ActorMethod<
    [string, string, string],
    Array<ExamRegRecord>
  >,
  'isShuffleUploaded' : ActorMethod<[string, string], boolean>,
  'restoreSnapshot' : ActorMethod<[string, string, string, string], boolean>,
  'setHODPermission' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'uploadCourses' : ActorMethod<
    [string, string, Array<CourseRecord>],
    undefined
  >,
  'uploadEnrollmentRecords' : ActorMethod<
    [string, string, string, Array<EnrollmentRecord>],
    boolean
  >,
  'uploadEnrollmentRecordsDean' : ActorMethod<
    [string, string, string, string, Array<EnrollmentRecord>],
    undefined
  >,
  'uploadExamRegRecords' : ActorMethod<
    [string, string, string, Array<ExamRegRecord>],
    boolean
  >,
  'uploadExamRegRecordsDean' : ActorMethod<
    [string, string, string, string, Array<ExamRegRecord>],
    undefined
  >,
  'uploadExamShuffleRecords' : ActorMethod<
    [string, string, string, string, Array<ExamShuffleRecord>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];