/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EnrollmentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'branch' : IDL.Text,
  'duration' : IDL.Text,
  'studentId' : IDL.Text,
  'yearKey' : IDL.Text,
  'errorDescription' : IDL.Text,
  'email' : IDL.Text,
  'errorType' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
  'college' : IDL.Text,
  'hasError' : IDL.Bool,
});
export const ExamRegRecord = IDL.Record({
  'id' : IDL.Text,
  'branch' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'studentId' : IDL.Text,
  'yearKey' : IDL.Text,
  'errorDescription' : IDL.Text,
  'email' : IDL.Text,
  'errorType' : IDL.Text,
  'registrationStatus' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
  'college' : IDL.Text,
  'hasError' : IDL.Bool,
});
export const CourseRecord = IDL.Record({
  'duration' : IDL.Text,
  'yearKey' : IDL.Text,
  'category' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
  'college' : IDL.Text,
});
export const EditedRecord = IDL.Record({
  'id' : IDL.Text,
  'field' : IDL.Text,
  'branch' : IDL.Text,
  'oldValue' : IDL.Text,
  'studentId' : IDL.Text,
  'yearKey' : IDL.Text,
  'newValue' : IDL.Text,
  'recordType' : IDL.Text,
  'timestamp' : IDL.Int,
  'editedBy' : IDL.Text,
  'college' : IDL.Text,
});
export const ExamShuffleRecord = IDL.Record({
  'id' : IDL.Text,
  'branch' : IDL.Text,
  'studentId' : IDL.Text,
  'yearKey' : IDL.Text,
  'examCenter' : IDL.Text,
  'email' : IDL.Text,
  'rollNo' : IDL.Text,
  'examDate' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
  'timeSlot' : IDL.Text,
  'college' : IDL.Text,
  'hallTicketNo' : IDL.Text,
  'seatingPosition' : IDL.Text,
});
export const HODPermission = IDL.Record({
  'branch' : IDL.Text,
  'yearKey' : IDL.Text,
  'editCredits' : IDL.Nat,
  'uploadCredits' : IDL.Nat,
  'college' : IDL.Text,
});
export const EnrollmentPage = IDL.Record({
  'hasMore' : IDL.Bool,
  'data' : IDL.Vec(EnrollmentRecord),
  'totalCount' : IDL.Nat,
});
export const ExamRegPage = IDL.Record({
  'hasMore' : IDL.Bool,
  'data' : IDL.Vec(ExamRegRecord),
  'totalCount' : IDL.Nat,
});
export const ExamShufflePage = IDL.Record({
  'hasMore' : IDL.Bool,
  'data' : IDL.Vec(ExamShuffleRecord),
  'totalCount' : IDL.Nat,
});
export const FileSnapshot = IDL.Record({
  'id' : IDL.Text,
  'isActive' : IDL.Bool,
  'filename' : IDL.Text,
  'timestamp' : IDL.Int,
  'recordCount' : IDL.Nat,
});
export const OverviewStats = IDL.Record({
  'examRegDoFirst' : IDL.Nat,
  'cleanEnrollment' : IDL.Nat,
  'totalEnrolled' : IDL.Nat,
  'examRegErrors' : IDL.Nat,
  'examRegDone' : IDL.Nat,
  'examRegRedo' : IDL.Nat,
  'enrollmentErrors' : IDL.Nat,
  'totalRegistered' : IDL.Nat,
});
export const BranchStats = IDL.Record({
  'branch' : IDL.Text,
  'examRegDoFirst' : IDL.Nat,
  'examRegErrors' : IDL.Nat,
  'examRegDone' : IDL.Nat,
  'examRegRedo' : IDL.Nat,
  'examRegTotal' : IDL.Nat,
  'enrollmentErrors' : IDL.Nat,
  'enrollmentTotal' : IDL.Nat,
});

export const idlService = IDL.Service({
  'editEnrollmentRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        EnrollmentRecord,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'editExamRegRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExamRegRecord,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'getAllCourses' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CourseRecord)],
      ['query'],
    ),
  'getAllEditedRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(EditedRecord)],
      ['query'],
    ),
  'getAllEnrollmentErrors' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(EnrollmentRecord)],
      ['query'],
    ),
  'getAllEnrollmentRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(EnrollmentRecord)],
      ['query'],
    ),
  'getAllExamRegErrors' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ExamRegRecord)],
      ['query'],
    ),
  'getAllExamRegRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ExamRegRecord)],
      ['query'],
    ),
  'getAllExamShuffle' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ExamShuffleRecord)],
      ['query'],
    ),
  'getAllHODPermissions' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(HODPermission)],
      ['query'],
    ),
  'getCoursesByBranchAndCollege' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(CourseRecord)],
      ['query'],
    ),
  'getEditedRecords' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(EditedRecord)],
      ['query'],
    ),
  'getEnrollmentByBranch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(EnrollmentRecord)],
      ['query'],
    ),
  'getEnrollmentRecordsPaged' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Nat,
        IDL.Nat,
      ],
      [EnrollmentPage],
      ['query'],
    ),
  'getExamRegByBranch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(ExamRegRecord)],
      ['query'],
    ),
  'getExamRegRecordsPaged' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Nat,
        IDL.Nat,
      ],
      [ExamRegPage],
      ['query'],
    ),
  'getExamShuffleByStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(ExamShuffleRecord)],
      ['query'],
    ),
  'getExamShufflePaged' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [ExamShufflePage],
      ['query'],
    ),
  'getFileSnapshots' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(FileSnapshot)],
      ['query'],
    ),
  'getHODPermission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(HODPermission)],
      ['query'],
    ),
  'getOverviewStats' : IDL.Func([IDL.Text, IDL.Text], [OverviewStats], []),
  'getStatsByBranch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [BranchStats],
      [],
    ),
  'getStudentEnrollment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(EnrollmentRecord)],
      ['query'],
    ),
  'getStudentExamReg' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(ExamRegRecord)],
      ['query'],
    ),
  'isShuffleUploaded' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'restoreSnapshot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setHODPermission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'uploadCourses' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(CourseRecord)],
      [],
      [],
    ),
  'uploadEnrollmentRecords' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(EnrollmentRecord)],
      [IDL.Bool],
      [],
    ),
  'uploadEnrollmentRecordsDean' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(EnrollmentRecord)],
      [],
      [],
    ),
  'uploadExamRegRecords' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExamRegRecord)],
      [IDL.Bool],
      [],
    ),
  'uploadExamRegRecordsDean' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExamRegRecord)],
      [],
      [],
    ),
  'uploadExamShuffleRecords' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExamShuffleRecord)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EnrollmentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'branch' : IDL.Text,
    'duration' : IDL.Text,
    'studentId' : IDL.Text,
    'yearKey' : IDL.Text,
    'errorDescription' : IDL.Text,
    'email' : IDL.Text,
    'errorType' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
    'college' : IDL.Text,
    'hasError' : IDL.Bool,
  });
  const ExamRegRecord = IDL.Record({
    'id' : IDL.Text,
    'branch' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'studentId' : IDL.Text,
    'yearKey' : IDL.Text,
    'errorDescription' : IDL.Text,
    'email' : IDL.Text,
    'errorType' : IDL.Text,
    'registrationStatus' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
    'college' : IDL.Text,
    'hasError' : IDL.Bool,
  });
  const CourseRecord = IDL.Record({
    'duration' : IDL.Text,
    'yearKey' : IDL.Text,
    'category' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
    'college' : IDL.Text,
  });
  const EditedRecord = IDL.Record({
    'id' : IDL.Text,
    'field' : IDL.Text,
    'branch' : IDL.Text,
    'oldValue' : IDL.Text,
    'studentId' : IDL.Text,
    'yearKey' : IDL.Text,
    'newValue' : IDL.Text,
    'recordType' : IDL.Text,
    'timestamp' : IDL.Int,
    'editedBy' : IDL.Text,
    'college' : IDL.Text,
  });
  const ExamShuffleRecord = IDL.Record({
    'id' : IDL.Text,
    'branch' : IDL.Text,
    'studentId' : IDL.Text,
    'yearKey' : IDL.Text,
    'examCenter' : IDL.Text,
    'email' : IDL.Text,
    'rollNo' : IDL.Text,
    'examDate' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
    'timeSlot' : IDL.Text,
    'college' : IDL.Text,
    'hallTicketNo' : IDL.Text,
    'seatingPosition' : IDL.Text,
  });
  const HODPermission = IDL.Record({
    'branch' : IDL.Text,
    'yearKey' : IDL.Text,
    'editCredits' : IDL.Nat,
    'uploadCredits' : IDL.Nat,
    'college' : IDL.Text,
  });
  const EnrollmentPage = IDL.Record({
    'hasMore' : IDL.Bool,
    'data' : IDL.Vec(EnrollmentRecord),
    'totalCount' : IDL.Nat,
  });
  const ExamRegPage = IDL.Record({
    'hasMore' : IDL.Bool,
    'data' : IDL.Vec(ExamRegRecord),
    'totalCount' : IDL.Nat,
  });
  const ExamShufflePage = IDL.Record({
    'hasMore' : IDL.Bool,
    'data' : IDL.Vec(ExamShuffleRecord),
    'totalCount' : IDL.Nat,
  });
  const FileSnapshot = IDL.Record({
    'id' : IDL.Text,
    'isActive' : IDL.Bool,
    'filename' : IDL.Text,
    'timestamp' : IDL.Int,
    'recordCount' : IDL.Nat,
  });
  const OverviewStats = IDL.Record({
    'examRegDoFirst' : IDL.Nat,
    'cleanEnrollment' : IDL.Nat,
    'totalEnrolled' : IDL.Nat,
    'examRegErrors' : IDL.Nat,
    'examRegDone' : IDL.Nat,
    'examRegRedo' : IDL.Nat,
    'enrollmentErrors' : IDL.Nat,
    'totalRegistered' : IDL.Nat,
  });
  const BranchStats = IDL.Record({
    'branch' : IDL.Text,
    'examRegDoFirst' : IDL.Nat,
    'examRegErrors' : IDL.Nat,
    'examRegDone' : IDL.Nat,
    'examRegRedo' : IDL.Nat,
    'examRegTotal' : IDL.Nat,
    'enrollmentErrors' : IDL.Nat,
    'enrollmentTotal' : IDL.Nat,
  });
  
  return IDL.Service({
    'editEnrollmentRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          EnrollmentRecord,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'editExamRegRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExamRegRecord,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'getAllCourses' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CourseRecord)],
        ['query'],
      ),
    'getAllEditedRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(EditedRecord)],
        ['query'],
      ),
    'getAllEnrollmentErrors' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(EnrollmentRecord)],
        ['query'],
      ),
    'getAllEnrollmentRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(EnrollmentRecord)],
        ['query'],
      ),
    'getAllExamRegErrors' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ExamRegRecord)],
        ['query'],
      ),
    'getAllExamRegRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ExamRegRecord)],
        ['query'],
      ),
    'getAllExamShuffle' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ExamShuffleRecord)],
        ['query'],
      ),
    'getAllHODPermissions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(HODPermission)],
        ['query'],
      ),
    'getCoursesByBranchAndCollege' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(CourseRecord)],
        ['query'],
      ),
    'getEditedRecords' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(EditedRecord)],
        ['query'],
      ),
    'getEnrollmentByBranch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(EnrollmentRecord)],
        ['query'],
      ),
    'getEnrollmentRecordsPaged' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Nat,
          IDL.Nat,
        ],
        [EnrollmentPage],
        ['query'],
      ),
    'getExamRegByBranch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(ExamRegRecord)],
        ['query'],
      ),
    'getExamRegRecordsPaged' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Nat,
          IDL.Nat,
        ],
        [ExamRegPage],
        ['query'],
      ),
    'getExamShuffleByStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(ExamShuffleRecord)],
        ['query'],
      ),
    'getExamShufflePaged' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [ExamShufflePage],
        ['query'],
      ),
    'getFileSnapshots' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(FileSnapshot)],
        ['query'],
      ),
    'getHODPermission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(HODPermission)],
        ['query'],
      ),
    'getOverviewStats' : IDL.Func([IDL.Text, IDL.Text], [OverviewStats], []),
    'getStatsByBranch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [BranchStats],
        [],
      ),
    'getStudentEnrollment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(EnrollmentRecord)],
        ['query'],
      ),
    'getStudentExamReg' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(ExamRegRecord)],
        ['query'],
      ),
    'isShuffleUploaded' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'restoreSnapshot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setHODPermission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'uploadCourses' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(CourseRecord)],
        [],
        [],
      ),
    'uploadEnrollmentRecords' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(EnrollmentRecord)],
        [IDL.Bool],
        [],
      ),
    'uploadEnrollmentRecordsDean' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(EnrollmentRecord)],
        [],
        [],
      ),
    'uploadExamRegRecords' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExamRegRecord)],
        [IDL.Bool],
        [],
      ),
    'uploadExamRegRecordsDean' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExamRegRecord)],
        [],
        [],
      ),
    'uploadExamShuffleRecords' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExamShuffleRecord)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };