/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CourseRecord {
    duration: string;
    yearKey: string;
    category: string;
    courseName: string;
    courseId: string;
    college: string;
}
export interface ExamShufflePage {
    hasMore: boolean;
    data: Array<ExamShuffleRecord>;
    totalCount: bigint;
}
export interface BranchStats {
    branch: string;
    examRegDoFirst: bigint;
    examRegErrors: bigint;
    examRegDone: bigint;
    examRegRedo: bigint;
    examRegTotal: bigint;
    enrollmentErrors: bigint;
    enrollmentTotal: bigint;
}
export interface HODPermission {
    branch: string;
    yearKey: string;
    editCredits: bigint;
    uploadCredits: bigint;
    college: string;
}
export interface FileSnapshot {
    id: string;
    isActive: boolean;
    filename: string;
    timestamp: bigint;
    recordCount: bigint;
}
export interface ExamShuffleRecord {
    id: string;
    branch: string;
    studentId: string;
    yearKey: string;
    examCenter: string;
    email: string;
    rollNo: string;
    examDate: string;
    courseName: string;
    courseId: string;
    timeSlot: string;
    college: string;
    hallTicketNo: string;
    seatingPosition: string;
}
export interface EnrollmentPage {
    hasMore: boolean;
    data: Array<EnrollmentRecord>;
    totalCount: bigint;
}
export interface EditedRecord {
    id: string;
    field: string;
    branch: string;
    oldValue: string;
    studentId: string;
    yearKey: string;
    newValue: string;
    recordType: string;
    timestamp: bigint;
    editedBy: string;
    college: string;
}
export interface ExamRegRecord {
    id: string;
    branch: string;
    paymentStatus: string;
    studentId: string;
    yearKey: string;
    errorDescription: string;
    email: string;
    errorType: string;
    registrationStatus: string;
    courseName: string;
    courseId: string;
    college: string;
    hasError: boolean;
}
export interface ExamRegPage {
    hasMore: boolean;
    data: Array<ExamRegRecord>;
    totalCount: bigint;
}
export interface OverviewStats {
    examRegDoFirst: bigint;
    cleanEnrollment: bigint;
    totalEnrolled: bigint;
    examRegErrors: bigint;
    examRegDone: bigint;
    examRegRedo: bigint;
    enrollmentErrors: bigint;
    totalRegistered: bigint;
}
export interface EnrollmentRecord {
    id: string;
    status: string;
    branch: string;
    duration: string;
    studentId: string;
    yearKey: string;
    errorDescription: string;
    email: string;
    errorType: string;
    courseName: string;
    courseId: string;
    college: string;
    hasError: boolean;
}
export interface backendInterface {
    editEnrollmentRecord(college: string, yearKey: string, branch: string, recordId: string, updated: EnrollmentRecord, editorId: string, field: string, oldValue: string, newValue: string): Promise<boolean>;
    editExamRegRecord(college: string, yearKey: string, branch: string, recordId: string, updated: ExamRegRecord, editorId: string, field: string, oldValue: string, newValue: string): Promise<boolean>;
    getAllCourses(college: string, yearKey: string): Promise<Array<CourseRecord>>;
    getAllEditedRecords(college: string, yearKey: string): Promise<Array<EditedRecord>>;
    getAllEnrollmentErrors(college: string, yearKey: string): Promise<Array<EnrollmentRecord>>;
    getAllEnrollmentRecords(college: string, yearKey: string): Promise<Array<EnrollmentRecord>>;
    getAllExamRegErrors(college: string, yearKey: string): Promise<Array<ExamRegRecord>>;
    getAllExamRegRecords(college: string, yearKey: string): Promise<Array<ExamRegRecord>>;
    getAllExamShuffle(college: string, yearKey: string): Promise<Array<ExamShuffleRecord>>;
    getAllHODPermissions(college: string, yearKey: string): Promise<Array<HODPermission>>;
    getCoursesByBranchAndCollege(college: string, yearKey: string, branch: string | null): Promise<Array<CourseRecord>>;
    getEditedRecords(college: string, yearKey: string, branch: string): Promise<Array<EditedRecord>>;
    getEnrollmentByBranch(college: string, yearKey: string, branch: string): Promise<Array<EnrollmentRecord>>;
    getEnrollmentRecordsPaged(college: string, yearKey: string, branch: string | null, errorOnly: boolean | null, offset: bigint, limit: bigint): Promise<EnrollmentPage>;
    getExamRegByBranch(college: string, yearKey: string, branch: string): Promise<Array<ExamRegRecord>>;
    getExamRegRecordsPaged(college: string, yearKey: string, branch: string | null, errorOnly: boolean | null, offset: bigint, limit: bigint): Promise<ExamRegPage>;
    getExamShuffleByStudent(college: string, yearKey: string, studentId: string): Promise<Array<ExamShuffleRecord>>;
    getExamShufflePaged(college: string, yearKey: string, offset: bigint, limit: bigint): Promise<ExamShufflePage>;
    getFileSnapshots(college: string, yearKey: string, fileType: string): Promise<Array<FileSnapshot>>;
    getHODPermission(college: string, yearKey: string, branch: string): Promise<HODPermission | null>;
    getOverviewStats(college: string, yearKey: string): Promise<OverviewStats>;
    getStatsByBranch(college: string, yearKey: string, branch: string): Promise<BranchStats>;
    getStudentEnrollment(college: string, yearKey: string, studentId: string): Promise<Array<EnrollmentRecord>>;
    getStudentExamReg(college: string, yearKey: string, studentId: string): Promise<Array<ExamRegRecord>>;
    isShuffleUploaded(college: string, yearKey: string): Promise<boolean>;
    restoreSnapshot(college: string, yearKey: string, fileType: string, snapshotId: string): Promise<boolean>;
    setHODPermission(college: string, yearKey: string, branch: string, uploadCredits: bigint, editCredits: bigint): Promise<void>;
    uploadCourses(_college: string, yearKey: string, records: Array<CourseRecord>): Promise<void>;
    uploadEnrollmentRecords(college: string, yearKey: string, branch: string, records: Array<EnrollmentRecord>): Promise<boolean>;
    uploadEnrollmentRecordsDean(college: string, yearKey: string, fileId: string, fileName: string, records: Array<EnrollmentRecord>): Promise<void>;
    uploadExamRegRecords(college: string, yearKey: string, branch: string, records: Array<ExamRegRecord>): Promise<boolean>;
    uploadExamRegRecordsDean(college: string, yearKey: string, fileId: string, fileName: string, records: Array<ExamRegRecord>): Promise<void>;
    uploadExamShuffleRecords(college: string, yearKey: string, fileId: string, fileName: string, records: Array<ExamShuffleRecord>): Promise<void>;
}
import type { HODPermission as _HODPermission } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async editEnrollmentRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: EnrollmentRecord, arg5: string, arg6: string, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editEnrollmentRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editEnrollmentRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async editExamRegRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExamRegRecord, arg5: string, arg6: string, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editExamRegRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editExamRegRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async getAllCourses(arg0: string, arg1: string): Promise<Array<CourseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses(arg0, arg1);
            return result;
        }
    }
    async getAllEditedRecords(arg0: string, arg1: string): Promise<Array<EditedRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEditedRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEditedRecords(arg0, arg1);
            return result;
        }
    }
    async getAllEnrollmentErrors(arg0: string, arg1: string): Promise<Array<EnrollmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnrollmentErrors(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnrollmentErrors(arg0, arg1);
            return result;
        }
    }
    async getAllEnrollmentRecords(arg0: string, arg1: string): Promise<Array<EnrollmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnrollmentRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnrollmentRecords(arg0, arg1);
            return result;
        }
    }
    async getAllExamRegErrors(arg0: string, arg1: string): Promise<Array<ExamRegRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExamRegErrors(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExamRegErrors(arg0, arg1);
            return result;
        }
    }
    async getAllExamRegRecords(arg0: string, arg1: string): Promise<Array<ExamRegRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExamRegRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExamRegRecords(arg0, arg1);
            return result;
        }
    }
    async getAllExamShuffle(arg0: string, arg1: string): Promise<Array<ExamShuffleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExamShuffle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExamShuffle(arg0, arg1);
            return result;
        }
    }
    async getAllHODPermissions(arg0: string, arg1: string): Promise<Array<HODPermission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHODPermissions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHODPermissions(arg0, arg1);
            return result;
        }
    }
    async getCoursesByBranchAndCollege(arg0: string, arg1: string, arg2: string | null): Promise<Array<CourseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByBranchAndCollege(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByBranchAndCollege(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getEditedRecords(arg0: string, arg1: string, arg2: string): Promise<Array<EditedRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEditedRecords(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEditedRecords(arg0, arg1, arg2);
            return result;
        }
    }
    async getEnrollmentByBranch(arg0: string, arg1: string, arg2: string): Promise<Array<EnrollmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentByBranch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentByBranch(arg0, arg1, arg2);
            return result;
        }
    }
    async getEnrollmentRecordsPaged(arg0: string, arg1: string, arg2: string | null, arg3: boolean | null, arg4: bigint, arg5: bigint): Promise<EnrollmentPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentRecordsPaged(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentRecordsPaged(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async getExamRegByBranch(arg0: string, arg1: string, arg2: string): Promise<Array<ExamRegRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamRegByBranch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamRegByBranch(arg0, arg1, arg2);
            return result;
        }
    }
    async getExamRegRecordsPaged(arg0: string, arg1: string, arg2: string | null, arg3: boolean | null, arg4: bigint, arg5: bigint): Promise<ExamRegPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamRegRecordsPaged(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamRegRecordsPaged(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async getExamShuffleByStudent(arg0: string, arg1: string, arg2: string): Promise<Array<ExamShuffleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamShuffleByStudent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamShuffleByStudent(arg0, arg1, arg2);
            return result;
        }
    }
    async getExamShufflePaged(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<ExamShufflePage> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamShufflePaged(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamShufflePaged(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getFileSnapshots(arg0: string, arg1: string, arg2: string): Promise<Array<FileSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileSnapshots(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileSnapshots(arg0, arg1, arg2);
            return result;
        }
    }
    async getHODPermission(arg0: string, arg1: string, arg2: string): Promise<HODPermission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHODPermission(arg0, arg1, arg2);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHODPermission(arg0, arg1, arg2);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverviewStats(arg0: string, arg1: string): Promise<OverviewStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverviewStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverviewStats(arg0, arg1);
            return result;
        }
    }
    async getStatsByBranch(arg0: string, arg1: string, arg2: string): Promise<BranchStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatsByBranch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatsByBranch(arg0, arg1, arg2);
            return result;
        }
    }
    async getStudentEnrollment(arg0: string, arg1: string, arg2: string): Promise<Array<EnrollmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentEnrollment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentEnrollment(arg0, arg1, arg2);
            return result;
        }
    }
    async getStudentExamReg(arg0: string, arg1: string, arg2: string): Promise<Array<ExamRegRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentExamReg(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentExamReg(arg0, arg1, arg2);
            return result;
        }
    }
    async isShuffleUploaded(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isShuffleUploaded(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isShuffleUploaded(arg0, arg1);
            return result;
        }
    }
    async restoreSnapshot(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreSnapshot(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreSnapshot(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setHODPermission(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHODPermission(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHODPermission(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async uploadCourses(arg0: string, arg1: string, arg2: Array<CourseRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCourses(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCourses(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadEnrollmentRecords(arg0: string, arg1: string, arg2: string, arg3: Array<EnrollmentRecord>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEnrollmentRecords(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEnrollmentRecords(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadEnrollmentRecordsDean(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<EnrollmentRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEnrollmentRecordsDean(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEnrollmentRecordsDean(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async uploadExamRegRecords(arg0: string, arg1: string, arg2: string, arg3: Array<ExamRegRecord>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadExamRegRecords(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadExamRegRecords(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadExamRegRecordsDean(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<ExamRegRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadExamRegRecordsDean(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadExamRegRecordsDean(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async uploadExamShuffleRecords(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<ExamShuffleRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadExamShuffleRecords(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadExamShuffleRecords(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HODPermission]): HODPermission | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
